### ISSUE TITLE
`as` keyword was removed in crystal 0.19

### ISSUE THREAD

**Issue by fridgerator** [dantebronto/crystal-api-backend#1]
Any idea how to implement a fix in [`build_from_sql.cr` line 8](https://github.com/dantebronto/crystal-api-backend/blob/master/src/concepts/database/build_from_sql.cr#L8) ?

**Comment by dantebronto** [comment]
Haven't had a chance to play with 0.19 yet. The release notes say "Removed the deprecated syntax x as T", but it's not clear what you're supposed to use instead. 

Does it work if you change line 8 to `object.{{prop}} = hash["{{prop}}"].as({{prop.type}})` ?

**Comment by dantebronto** [comment]
It should be working on 0.19 now.

**Comment by fridgerator** [comment]
awesome, thanks!

BTW, I like some of your concepts you have implemented here.  For instance the Repo (repository), seems a nice abstraction from the model layer similar to [Phoenix](http://www.phoenixframework.org/)

**Comment by dantebronto** [comment]
Awesome, thanks for looking! I haven't looked at Phoneix much yet, but I assume we're coming from a similar place of having worked on a lot of Rails apps that can get out of control because of lack of architectural discipline.
